export const skills = [
    // Software Development and Programming
    "Python",
    "Java",
    "JavaScript",
    "C++",
    "C#",
    "Ruby",
    "Swift",
    "Go",
    "PHP",
    "HTML",
    "CSS",
    "Kotlin",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
    "Git",
    "RESTful API Design",
    "Django",
    "Spring Framework",
    "Express.js",
    "ASP.NET",
    "Scala",
    "TypeScript",
    "Rust",

    // Data Analysis and Statistics
    "Statistical Analysis",
    "SQL",
    "R",
    "Excel",
    "Tableau",
    "Power BI",
    "MATLAB",
    "SAS",
    "Database Management",
    "Pandas",
    "NumPy",
    "Scikit-learn",
    "Jupyter Notebook",
    "Data Visualization",

    // Artificial Intelligence (AI) and Machine Learning (ML)
    "Machine Learning Algorithms",
    "Deep Learning Architecture",
    "Natural Language Processing",
    "OpenCV",
    "TensorFlow",
    "PyTorch",
    "OpenAI Gym",
    "Stable Baselines",
    "RLlib",
    "Neural Networks",
    "Reinforcement Learning",
    "GANs (Generative Adversarial Networks)",

    // Cloud Computing
    "Amazon Web Services",
    "Microsoft Azure",
    "Google Cloud Platform",
    "IBM Cloud",
    "Cloud Infrastructure",
    "Containerization",
    "Docker",
    "Kubernetes",
    "Serverless Computing",
    "AWS Lambda",
    "Azure Functions",
    "Terraform",
    "Cloud Security",

    // Cybersecurity
    "Network Security",
    "Network Protocols",
    "Firewalls",
    "Intrusion Detection Systems",
    "Intrusion Prevention Systems",
    "Virtual Private Networks",
    "Vulnerability Assessment",
    "Penetration Testing",
    "Incident Response",
    "Digital Forensics",
    "Ethical Hacking",
    "Security Auditing",
    "Cryptocurrency Security",

    // Project Management
    "Project Planning",
    "Project Scheduling",
    "Project Budgeting",
    "Cost Management",
    "Risk Management",
    "Project Documentation",
    "Project Charters",
    "Stakeholder Communication Plans",
    "Change Management",
    "Project Closure",
    "Project Evaluation",
    "Agile Methodologies",
    "Scrum",
    "Kanban",
    "Lean Methodology",

    // Digital Marketing
    "Search Engine Optimization",
    "Search Engine Marketing",
    "Google Ads",
    "Social Media Marketing",
    "Content Marketing",
    "Blog Writing",
    "A/B Testing",
    "Marketing Automation",
    "Conversion Rate Optimization",
    "User Experience Optimization",
    "Influencer Marketing",
    "Email Marketing",
    "Marketing Analytics",

    // Graphic Design
    "Adobe Creative Suite",
    "Typography",
    "Layout Design",
    "Color Theory",
    "Visual Brand Identities",
    "Illustration",
    "Custom Graphics",
    "Image Editing and Retouching",
    "Print Design",
    "User Interface Design",
    "Web Design",
    "Motion Graphics",

    // UX/UI Design
    "User Interviews",
    "Surveys and Questionnaires",
    "Usability Testing",
    "Information Design",
    "Wireframing",
    "Interaction Design",
    "Prototyping",
    "Adobe XD",
    "Sketch",
    "Figma",
    "InVision",
    "Heatmaps",
    "Responsive Design",
    "Accessibility Design",
    "User Research",
    "User Persona Creation",

    // Financial Analysis
    "Financial Statement Analysis",
    "Financial Ratio Analysis",
    "Financial Modeling",
    "Valuation Techniques",
    "Capital Budgeting",
    "Financial Forecasting",
    "Investment Analysis",
    "Corporate Finance",
    "Financial modeling software",
    "Statistical analysis software",
    "Data visualization tools",
    "Econometrics",
    "Monte Carlo Simulation",

    // Foreign Languages
    "Grammar",
    "Syntax",
    "Vocabulary Building",
    "Writing Skills",
    "Translation",
    "Language Teaching",
    "Language Technology Tools",
    "Niche Language Knowledge",
    "Interpersonal Communication",

    // Soft Skills
    "Active Listening",
    "Verbal Communication",
    "Nonverbal Communication",
    "Written Communication",
    "Empathy",
    "Emotional Intelligence",
    "Interpersonal Skills",
    "Collaboration",
    "Conflict Resolution",
    "Building Positive Relationships",
    "Stakeholder Management",
    "Presentation",
    "Negotiation",
    "Adaptability",
    "Clarity",
    "Respectful Communication",
    "Constructive Feedback",
    "Handling Criticism",
    "Cultural Awareness",
    "Teamwork",
    "Problem-Solving",
    "Flexibility",
    "Respect",
    "Trust Building",
    "Leadership",
    "Time Management",
    "Decision-Making",
    "Networking",
    "Accountability",
    "Mediation",
    "Relationship Building",
    "Diplomacy",
    "Active Engagement",
    "Delegation",
    "Critical Thinking",
    "Analytical Skills",
    "Data Assessment",
    "Evaluation",
    "Creativity",
    "Problem Analysis",
    "Research",
    "Open-Minded",
    "Persistence",
    "Task Prioritization",
    "Managing Resources",
    "Resourcefulness",
    "Agility",
    "Systematic Thinking",
    "Identifying Patterns",
    "Reasoning",
    "Logical and Rational Thinking Processes",
    "Data-Based Decision-Making",
    "Reflection",
    "Self-Reflection",
    "Curiosity",
    "Information Evaluation",
    "Identifying the Root Cause of the Problem",
    "Critical Reading",
    "Evidence-Based Reasoning",
    "Objectivity",
    "Creative Thinking",
    "Effective Communication",
    "Resilience",
    "Proactivity",
    "Ability to Adjust",
    "Open-Mindedness",
    "Learning Agility",
    "Initiative",
    "Self-Motivation",
    "Versatility",
    "Accommodating Change",
    "Thriving in Diverse Environments",
    "Self-Confidence",
    "Inspiration",
    "Navigating Challenges and Change",
    "Understanding Different Perspectives",
    "Compassion",
    "Vision",
    "Taking Responsibility",
    "Coaching",
    "Mentoring",
    "Providing Feedback",
    "Integrity",
    "Honesty",
    "Transparency",
    "Work Ethics",
    "Influence",
    "Empowerment",
    "Personal and Professional Development",
    "Fostering a Culture of Growth",
    "Strategizing",
    "Prioritization",
    "Attention to Detail",
    "Multitasking",
    "Task Delegation",
    "Workflow Optimization",
    "Documentation",
    "Record-Keeping",
    "Goal Setting",
    "Developing Effective Solutions",
    "Conveying Information",
    "Critical Analysis",
    "Evaluating Risks",
    "Adaptation to Technology",
    "Understanding",
    "Persuasion",
    "Exploring Alternative Solutions",
    "Finding Win-Win Outcomes",
    "Adapting Negotiation Strategies",
    "Assertiveness",
    "Cooperation",
    "Patience",
    "Brainstorming",
    "Evaluating Potential Outcomes",
    "Preparation",
    "Managing Conflict",
    "Compromise",
    "Confidence",
    "Unconventional Thinking",
    "Finding Innovative Solutions",
    "Taking Calculated Risks",
    "Stepping Out of Comfort Zone",
    "Entrepreneurial Mindset",
    "Seeking Opportunities for Growth",
    "Growth Mindset",
    "Mutual Understanding",
    "Constructively Addressing Conflicts",
    "Valuing Diverse Perspectives",
    "Adjusting Behavior to Establish Rapport",
    "Cultural Sensitivity",
    "Trustworthiness",
    "Fostering Credibility",
    "Sharing Responsibilities",
    "Valuing Contributions",
    "Public Speaking",
    "Strong Stage Presence",
    "Audience Engagement",
    "Storytelling"
];