const skills = [
    // Software Development and Programming
    "Python",
    "Java",
    "JavaScript",
    "C++",
    "C#",
    "Ruby",
    "Swift",
    "Go",
    "PHP",
    "HTML",
    "CSS",
    "Java or Kotlin for Android apps",
    "React",
    "Angular",
    "Vue.js",
    "Node.js",
   
    // Data Analysis and Statistics
    "Statistical Analysis",
    "SQL",
    "Python (with libraries like pandas)",
    "R (with packages like dplyr)",
    "Excel",
    "Tableau",
    "Power BI",
    "MATLAB",
    "SAS",
    "Database Management",
   
    // Artificial Intelligence (AI) and Machine Learning (ML)
    "Machine Learning Algorithms",
    "Deep Learning Architecture",
    "Natural Language Processing (NLP)",
    "OpenCV",
    "TensorFlow",
    "PyTorch",
    "OpenAI Gym",
    "Stable Baselines",
    "RLlib",
   
    // Cloud Computing
    "Amazon Web Services (AWS)",
    "Microsoft Azure",
    "Google Cloud Platform (GCP)",
    "IBM Cloud",
    "Cloud Infrastructure",
    "Containerization",
    "Docker",
    "Kubernetes",
    "Serverless Computing",
    "AWS Lambda",
    "Azure Functions",
   
    // Cybersecurity
    "Network Security",
    "Network protocols",
    "Firewalls",
    "Intrusion detection systems (IDS)",
    "Intrusion prevention systems (IPS)",
    "Virtual private networks (VPNs)",
    "Vulnerability Assessment",
    "Penetration Testing",
    "Incident Response",
    "Digital Forensics",
   
    // Project Management
    "Project Planning",
    "Project Scheduling",
    "Project Budgeting",
    "Cost Management",
    "Risk Management",
    "Project Documentation",
    "Project charters",
    "Stakeholder communication plans",
    "Change Management",
    "Project Closure",
    "Project Evaluation",
   
    // Digital Marketing
    "Search Engine Optimization (SEO)",
    "Search Engine Marketing (SEM)",
    "Google Ads",
    "Social Media Marketing",
    "Content Marketing",
    "Blog writing",
    "A/B Testing",
    "Marketing Automation",
    "Conversion Rate Optimization (CRO)",
    "User Experience (UX) Optimization",
    "Influencer Marketing",
   
    // Graphic Design
    "Adobe Creative Suite",
    "Typography",
    "Layout Design",
    "Color Theory",
    "Visual brand identities",
    "Illustration",
    "Custom graphics",
    "Image Editing and Retouching",
    "Print Design",
    "User Interface (UI) Design",
    "Web Design",
   
    // UX/UI Design
    "User Interviews",
    "Surveys and Questionnaires",
    "Usability Testing",
    "Information Design",
    "Wireframing",
    "Interaction Design",
    "Prototyping",
    "Adobe XD",
    "Sketch",
    "Figma",
    "InVision",
    "Typography and Layout",
    "Heatmaps",
    "Data Analysis",
    "Google Analytics",
    "Mixpanel",
    "Responsive Design",
    "Accessibility Design",
   
    // Financial Analysis
    "Financial Statement Analysis",
    "Financial Ratio Analysis",
    "Financial Modeling",
    "Valuation Techniques",
    "Risk Analysis",
    "Capital Budgeting",
    "Cost Analysis",
    "Financial Forecasting",
    "Investment Analysis",
    "Corporate Finance",
    "Financial modeling software",
    "Statistical analysis software",
    "Data visualization tools",
   
    // Foreign Languages
    "Grammar",
    "Syntax",
    "Vocabulary Building",
    "Writing Skills",
    "Translation",
    "Language Teaching",
    "Language Technology Tools",
    "Niche Language Knowledge",
    "Interpersonal Communication",
   
    // Soft Skills
    "Active listening",
    "Verbal communication",
    "Nonverbal communication",
    "Written communication",
    "Empathy",
    "Emotional intelligence",
    "Interpersonal skills",
    "Collaboration",
    "Conflict resolution",
    "Building positive relationships",
    "Stakeholder management",
    "Presentation",
    "Negotiation",
    "Adaptability",
    "Clarity",
    "Respectful communication",
    "Constructive feedback",
    "Handling criticism",
    "Cultural awareness",
    "Teamwork",
    "Problem-solving",
    "Flexibility",
    "Respect",
    "Trust building",
    "Leadership",
    "Time management",
    "Decision-making",
    "Networking",
    "Accountability",
    "Mediation",
    "Relationship building",
    "Diplomacy",
    "Active engagement",
    "Delegation",
    "Critical thinking",
    "Analytical skills",
    "Data assessment",
    "Evaluation",
    "Creativity",
    "Problem analysis",
    "Research",
    "Open-minded",
    "Persistence",
    "Task prioritization",
    "Managing resources",
    "Resourcefulness",
    "Agility",
    "Systematic thinking",
    "Identifying patterns",
    "Reasoning",
    "Logical and rational thinking processes",
    "Data-based decision-making",
    "Reflection",
    "Self-reflection",
    "Curiosity",
    "Information evaluation",
    "Identifying the root cause of the problem",
    "Critical reading",
    "Evidence-based reasoning",
    "Objectivity",
    "Creative thinking",
    "Effective Communication",
    "Resilience",
    "Proactivity",
    "Ability to adjust",
    "Open-mindedness",
    "Learning agility",
    "Initiative",
    "Self-motivation",
    "Versatility",
    "Accommodating change",
    "Thriving in diverse environments",
    "Self-confidence",
    "Inspiration",
    "Navigating challenges and change",
    "Understanding different perspectives",
    "Compassion",
    "Vision",
    "Taking responsibility",
    "Coaching",
    "Mentoring",
    "Providing feedback",
    "Integrity",
    "Honesty",
    "Transparency",
    "Work ethics",
    "Influence",
    "Empowerment",
    "Personal and professional development",
    "Fostering a culture of growth",
    "Strategizing",
    "Prioritization",
    "Attention to detail",
    "Multitasking",
    "Task delegation",
    "Workflow optimization",
    "Documentation",
    "Record-keeping",
    "Goal setting",
    "Developing effective solutions",
    "Conveying information",
    "Critical analysis",
    "Evaluating risks",
    "Adaptation to technology",
    "Understanding",
    "Persuasion",
    "Exploring alternative solutions",
    "Finding win-win outcomes",
    "Adapting negotiation strategies",
    "Assertiveness",
    "Cooperation",
    "Patience",
    "Brainstorming",
    "Evaluating potential outcomes",
    "Preparation",
    "Managing conflict",
    "Compromise",
    "Confidence",
    "Unconventional thinking",
    "Finding innovative solutions",
    "Open to new ideas",
    "Embracing diverse viewpoints",
    "Strong desire to explore",
    "Articulating ideas",
    "Perseverance",
    "Taking calculated risks",
    "Stepping out of comfort zone",
    "Entrepreneurial mindset",
    "Seeking opportunities for growth",
    "Growth mindset",
    "Mutual understanding",
    "Constructively addressing conflicts",
    "Valuing diverse perspectives",
    "Adjusting behavior to establish rapport",
    "Cultural sensitivity",
    "Trustworthiness",
    "Fostering credibility",
    "Sharing responsibilities",
    "Valuing contributions",
    "Public speaking",
    "Strong stage presence",
    "Audience engagement",
    "Storytelling",
    "Visual design"]